-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.entertainment;

CREATE TABLE IF NOT EXISTS public.entertainment
(
    entertainment character varying(200) COLLATE pg_catalog."default",
    city character varying(50) COLLATE pg_catalog."default",
    postcode integer,
    housenumber character varying COLLATE pg_catalog."default",
    street character varying(200) COLLATE pg_catalog."default",
    state character varying(20) COLLATE pg_catalog."default",
    entertainment_address character varying(200) COLLATE pg_catalog."default",
    entertainment_longitude numeric,
    latitude numeric,
    id integer NOT NULL DEFAULT 'nextval('entertainment_id_seq'::regclass)',
    CONSTRAINT entertainment_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.hotels;

CREATE TABLE IF NOT EXISTS public.hotels
(
    "Hotel Name" character varying(200) COLLATE pg_catalog."default",
    city character varying(50) COLLATE pg_catalog."default",
    postcode integer,
    housenumber character varying COLLATE pg_catalog."default",
    street character varying(50) COLLATE pg_catalog."default",
    state character varying COLLATE pg_catalog."default",
    hotel_address character varying(200) COLLATE pg_catalog."default",
    hotel_longitude numeric,
    hotel_latitude numeric,
    id integer NOT NULL DEFAULT 'nextval('hotels_id_seq'::regclass)',
    CONSTRAINT hotels_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.transportation;

CREATE TABLE IF NOT EXISTS public.transportation
(
    name character varying(200) COLLATE pg_catalog."default",
    city character varying(20) COLLATE pg_catalog."default",
    postcode integer,
    street character varying(50) COLLATE pg_catalog."default",
    transp_address character varying(200) COLLATE pg_catalog."default",
    "Transport_Type" character varying(200) COLLATE pg_catalog."default",
    "Transport" character varying COLLATE pg_catalog."default",
    "Route" character varying COLLATE pg_catalog."default",
    transp_longitude numeric,
    transp_latitude numeric,
    id integer NOT NULL DEFAULT 'nextval('transportation_id_seq'::regclass)',
    CONSTRAINT transportation_pkey PRIMARY KEY (id)
);
END;